# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Blog
email: jeremyrajan@gmail.com
description: 'Software Engineer by day, freelancer by night. I love application
  development, something which I am passionate about. <br/>
  <slogan>Love What You Do!</slogan>'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeremyrajan.github.io" # the base hostname & protocol for your site
twitter_username: jeremyrajan
github_username:  jeremyrajan

# Build settings
markdown: kramdown
